### ISSUE TITLE
bug: incorrect handling of non-docker paths for corgie_image

### ISSUE THREAD

**Issue by macrintr** [ZettaAI/seuron#5]
When running a corgie command the updates `corgie_image`, the path is incorrectly parsed if it's a non-docker path. For example passing `us.gcr.io/CONTAINER_PATH` sets the variable `corgie_image` to `http://us.gcr.io/CONTAINER_PATH|us.gcr.io/CONTAINER_PATH`.

**Comment by nicholasturner1** [comment]
Ok. Is the `|` character part of the stored variable? I'm confused. If not, can you give an explicit example of the input, the expected output and the actual output?

**Comment by nicholasturner1** [comment]
Nevermind. I see an example in your slack message. I don't see how this happens yet, but I'll look into it.
